services:
  app:
    container_name: sandol-classroom-timetable-app
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/lecture_array.json:/app/data/lecture_array.json:ro
      - ./data/buildings.csv:/app/data/buildings.csv:ro
    networks:
      - sandol-network

networks:
  sandol-network:
    driver: bridge

volumes:
  db_data:
