services:
  app:
    container_name: sandol-classroom-timetable-app
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "80:8080"
    networks:
      - sandol-network

networks:
  sandol-network:
    driver: bridge

volumes:
  db_data:
